title: ngld OverlayPlugin
description: >- # this means to ignore newlines until "baseurl:"
  Yet another OverlayPlugin fork.
baseurl: "/OverlayPlugin"
url: "https://ngld.github.io/OverlayPlugin"
github_username: ngld
repository: ngld/OverlayPlugin

# Build settings
#theme: jekyll-text-theme
remote_theme: kitian616/jekyll-TeXt-theme
text_skin: dark
highlight_theme: tomorrow-night

permalinks: pretty
plugins: []

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_hightlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
